// 学年別 漢字データ(代表的な漢字セット)
// words: その漢字を使った単語。reading = 単語全体のひらがな、answer = 正解の書き表し(漢字+送り仮名)
const KANJI_DATA = [
  // ===== 1年生 =====
  { kanji: '一', grade: 1, words: [ { reading: 'ひとつ', answer: '一つ' }, { reading: 'いちねん', answer: '一年' } ] },
  { kanji: '二', grade: 1, words: [ { reading: 'ふたつ', answer: '二つ' }, { reading: 'にがつ', answer: '二月' } ] },
  { kanji: '三', grade: 1, words: [ { reading: 'みっつ', answer: '三つ' }, { reading: 'さんにん', answer: '三人' } ] },
  { kanji: '大', grade: 1, words: [ { reading: 'おおきい', answer: '大きい' }, { reading: 'たいせつ', answer: '大切' } ] },
  { kanji: '小', grade: 1, words: [ { reading: 'ちいさい', answer: '小さい' }, { reading: 'しょうがっこう', answer: '小学校' } ] },
  { kanji: '人', grade: 1, words: [ { reading: 'ひと', answer: '人' }, { reading: 'にんき', answer: '人気' } ] },
  { kanji: '山', grade: 1, words: [ { reading: 'やま', answer: '山' }, { reading: 'とざん', answer: '登山' } ] },
  { kanji: '川', grade: 1, words: [ { reading: 'かわ', answer: '川' }, { reading: 'おがわ', answer: '小川' } ] },
  { kanji: '水', grade: 1, words: [ { reading: 'みず', answer: '水' }, { reading: 'すいえい', answer: '水泳' } ] },
  { kanji: '火', grade: 1, words: [ { reading: 'ひ', answer: '火' }, { reading: 'かじ', answer: '火事' } ] },
  { kanji: '木', grade: 1, words: [ { reading: 'き', answer: '木' }, { reading: 'もくようび', answer: '木曜日' } ] },
  { kanji: '金', grade: 1, words: [ { reading: 'きん', answer: '金' }, { reading: 'おかね', answer: 'お金' } ] },
  { kanji: '土', grade: 1, words: [ { reading: 'つち', answer: '土' }, { reading: 'どようび', answer: '土曜日' } ] },
  { kanji: '日', grade: 1, words: [ { reading: 'ひ', answer: '日' }, { reading: 'にちようび', answer: '日曜日' } ] },
  { kanji: '月', grade: 1, words: [ { reading: 'つき', answer: '月' }, { reading: 'げつようび', answer: '月曜日' } ] },
  { kanji: '年', grade: 1, words: [ { reading: 'とし', answer: '年' }, { reading: 'いちねんせい', answer: '一年生' } ] },
  { kanji: '天', grade: 1, words: [ { reading: 'てん', answer: '天' }, { reading: 'てんき', answer: '天気' } ] },
  { kanji: '雨', grade: 1, words: [ { reading: 'あめ', answer: '雨' }, { reading: 'おおあめ', answer: '大雨' } ] },
  { kanji: '花', grade: 1, words: [ { reading: 'はな', answer: '花' }, { reading: 'はなび', answer: '花火' } ] },
  { kanji: '学', grade: 1, words: [ { reading: 'まなぶ', answer: '学ぶ' }, { reading: 'がっこう', answer: '学校' } ] },

  // ===== 2年生 =====
  { kanji: '引', grade: 2, words: [ { reading: 'ひく', answer: '引く' }, { reading: 'いんりょく', answer: '引力' } ] },
  { kanji: '雲', grade: 2, words: [ { reading: 'くも', answer: '雲' }, { reading: 'うんかい', answer: '雲海' } ] },
  { kanji: '何', grade: 2, words: [ { reading: 'なに', answer: '何' }, { reading: 'なんにん', answer: '何人' } ] },
  { kanji: '夏', grade: 2, words: [ { reading: 'なつ', answer: '夏' }, { reading: 'なつやすみ', answer: '夏休み' } ] },
  { kanji: '家', grade: 2, words: [ { reading: 'いえ', answer: '家' }, { reading: 'かぞく', answer: '家族' } ] },
  { kanji: '歌', grade: 2, words: [ { reading: 'うた', answer: '歌' }, { reading: 'うたう', answer: '歌う' } ] },
  { kanji: '絵', grade: 2, words: [ { reading: 'え', answer: '絵' }, { reading: 'えほん', answer: '絵本' } ] },
  { kanji: '教', grade: 2, words: [ { reading: 'おしえる', answer: '教える' }, { reading: 'きょうしつ', answer: '教室' } ] },
  { kanji: '近', grade: 2, words: [ { reading: 'ちかい', answer: '近い' }, { reading: 'きんじょ', answer: '近所' } ] },
  { kanji: '兄', grade: 2, words: [ { reading: 'あに', answer: '兄' }, { reading: 'おにいさん', answer: 'お兄さん' } ] },
  { kanji: '計', grade: 2, words: [ { reading: 'はかる', answer: '計る' }, { reading: 'けいさん', answer: '計算' } ] },
  { kanji: '古', grade: 2, words: [ { reading: 'ふるい', answer: '古い' }, { reading: 'ちゅうこ', answer: '中古' } ] },
  { kanji: '後', grade: 2, words: [ { reading: 'あと', answer: '後' }, { reading: 'ごご', answer: '午後' } ] },
  { kanji: '語', grade: 2, words: [ { reading: 'かたる', answer: '語る' }, { reading: 'にほんご', answer: '日本語' } ] },
  { kanji: '広', grade: 2, words: [ { reading: 'ひろい', answer: '広い' }, { reading: 'ひろば', answer: '広場' } ] },
  { kanji: '考', grade: 2, words: [ { reading: 'かんがえる', answer: '考える' }, { reading: 'さんこう', answer: '参考' } ] },
  { kanji: '高', grade: 2, words: [ { reading: 'たかい', answer: '高い' }, { reading: 'こうこう', answer: '高校' } ] },
  { kanji: '黒', grade: 2, words: [ { reading: 'くろい', answer: '黒い' }, { reading: 'こくばん', answer: '黒板' } ] },
  { kanji: '今', grade: 2, words: [ { reading: 'いま', answer: '今' }, { reading: 'こんげつ', answer: '今月' } ] },
  { kanji: '思', grade: 2, words: [ { reading: 'おもう', answer: '思う' }, { reading: 'いし', answer: '意思' } ] },

  // ===== 3年生 =====
  { kanji: '有', grade: 3, words: [ { reading: 'ゆうめい', answer: '有名' }, { reading: 'ゆうりょう', answer: '有料' } ] },
  { kanji: '泳', grade: 3, words: [ { reading: 'およぐ', answer: '泳ぐ' }, { reading: 'すいえい', answer: '水泳' } ] },
  { kanji: '駅', grade: 3, words: [ { reading: 'えき', answer: '駅' }, { reading: 'えきいん', answer: '駅員' } ] },
  { kanji: '曲', grade: 3, words: [ { reading: 'まがる', answer: '曲がる' }, { reading: 'きょく', answer: '曲' } ] },
  { kanji: '銀', grade: 3, words: [ { reading: 'ぎん', answer: '銀' }, { reading: 'ぎんこう', answer: '銀行' } ] },
  { kanji: '決', grade: 3, words: [ { reading: 'きめる', answer: '決める' }, { reading: 'けっしん', answer: '決心' } ] },
  { kanji: '県', grade: 3, words: [ { reading: 'けん', answer: '県' }, { reading: 'けんちょう', answer: '県庁' } ] },
  { kanji: '港', grade: 3, words: [ { reading: 'みなと', answer: '港' }, { reading: 'くうこう', answer: '空港' } ] },
  { kanji: '祭', grade: 3, words: [ { reading: 'まつり', answer: '祭り' }, { reading: 'まつる', answer: '祭る' } ] },
  { kanji: '使', grade: 3, words: [ { reading: 'つかう', answer: '使う' }, { reading: 'しよう', answer: '使用' } ] },
  { kanji: '始', grade: 3, words: [ { reading: 'はじめる', answer: '始める' }, { reading: 'かいし', answer: '開始' } ] },
  { kanji: '持', grade: 3, words: [ { reading: 'もつ', answer: '持つ' }, { reading: 'きもち', answer: '気持ち' } ] },
  { kanji: '取', grade: 3, words: [ { reading: 'とる', answer: '取る' }, { reading: 'しゅとく', answer: '取得' } ] },
  { kanji: '受', grade: 3, words: [ { reading: 'うける', answer: '受ける' }, { reading: 'じゅけん', answer: '受験' } ] },
  { kanji: '拾', grade: 3, words: [ { reading: 'ひろう', answer: '拾う' }, { reading: 'ひろいもの', answer: '拾い物' } ] },
  { kanji: '終', grade: 3, words: [ { reading: 'おわる', answer: '終わる' }, { reading: 'しゅうてん', answer: '終点' } ] },
  { kanji: '集', grade: 3, words: [ { reading: 'あつまる', answer: '集まる' }, { reading: 'しゅうごう', answer: '集合' } ] },
  { kanji: '重', grade: 3, words: [ { reading: 'おもい', answer: '重い' }, { reading: 'じゅうよう', answer: '重要' } ] },
  { kanji: '消', grade: 3, words: [ { reading: 'けす', answer: '消す' }, { reading: 'しょうぼう', answer: '消防' } ] },
  { kanji: '勝', grade: 3, words: [ { reading: 'かつ', answer: '勝つ' }, { reading: 'しょうり', answer: '勝利' } ] },

  // ===== 4年生 =====
  { kanji: '愛', grade: 4, words: [ { reading: 'あい', answer: '愛' }, { reading: 'あいじょう', answer: '愛情' } ] },
  { kanji: '以', grade: 4, words: [ { reading: 'いか', answer: '以下' }, { reading: 'いじょう', answer: '以上' } ] },
  { kanji: '位', grade: 4, words: [ { reading: 'くらい', answer: '位' }, { reading: 'じゅんい', answer: '順位' } ] },
  { kanji: '英', grade: 4, words: [ { reading: 'えいご', answer: '英語' }, { reading: 'えいこく', answer: '英国' } ] },
  { kanji: '塩', grade: 4, words: [ { reading: 'しお', answer: '塩' }, { reading: 'しおあじ', answer: '塩味' } ] },
  { kanji: '加', grade: 4, words: [ { reading: 'くわえる', answer: '加える' }, { reading: 'さんか', answer: '参加' } ] },
  { kanji: '完', grade: 4, words: [ { reading: 'かんせい', answer: '完成' }, { reading: 'かんりょう', answer: '完了' } ] },
  { kanji: '泣', grade: 4, words: [ { reading: 'なく', answer: '泣く' }, { reading: 'なきごえ', answer: '泣き声' } ] },
  { kanji: '季', grade: 4, words: [ { reading: 'きせつ', answer: '季節' }, { reading: 'しき', answer: '四季' } ] },
  { kanji: '協', grade: 4, words: [ { reading: 'きょうりょく', answer: '協力' }, { reading: 'きょうかい', answer: '協会' } ] },
  { kanji: '結', grade: 4, words: [ { reading: 'むすぶ', answer: '結ぶ' }, { reading: 'けっか', answer: '結果' } ] },
  { kanji: '健', grade: 4, words: [ { reading: 'けんこう', answer: '健康' }, { reading: 'けんぜん', answer: '健全' } ] },
  { kanji: '好', grade: 4, words: [ { reading: 'すき', answer: '好き' }, { reading: 'こうかん', answer: '好感' } ] },
  { kanji: '最', grade: 4, words: [ { reading: 'もっとも', answer: '最も' }, { reading: 'さいこう', answer: '最高' } ] },
  { kanji: '残', grade: 4, words: [ { reading: 'のこる', answer: '残る' }, { reading: 'ざんねん', answer: '残念' } ] },
  { kanji: '借', grade: 4, words: [ { reading: 'かりる', answer: '借りる' }, { reading: 'しゃっきん', answer: '借金' } ] },
  { kanji: '初', grade: 4, words: [ { reading: 'はじめて', answer: '初めて' }, { reading: 'さいしょ', answer: '最初' } ] },
  { kanji: '笑', grade: 4, words: [ { reading: 'わらう', answer: '笑う' }, { reading: 'えがお', answer: '笑顔' } ] },
  { kanji: '信', grade: 4, words: [ { reading: 'しんじる', answer: '信じる' }, { reading: 'じしん', answer: '自信' } ] },
  { kanji: '戦', grade: 4, words: [ { reading: 'たたかう', answer: '戦う' }, { reading: 'せんそう', answer: '戦争' } ] },

  // ===== 5年生 =====
  { kanji: '圧', grade: 5, words: [ { reading: 'あっしゅく', answer: '圧縮' }, { reading: 'きあつ', answer: '気圧' } ] },
  { kanji: '河', grade: 5, words: [ { reading: 'かわ', answer: '河' }, { reading: 'かせん', answer: '河川' } ] },
  { kanji: '格', grade: 5, words: [ { reading: 'ごうかく', answer: '合格' }, { reading: 'かっこう', answer: '格好' } ] },
  { kanji: '眼', grade: 5, words: [ { reading: 'めがね', answer: '眼鏡' }, { reading: 'がんか', answer: '眼科' } ] },
  { kanji: '基', grade: 5, words: [ { reading: 'もとづく', answer: '基づく' }, { reading: 'きほん', answer: '基本' } ] },
  { kanji: '規', grade: 5, words: [ { reading: 'きそく', answer: '規則' }, { reading: 'きぼ', answer: '規模' } ] },
  { kanji: '経', grade: 5, words: [ { reading: 'へる', answer: '経る' }, { reading: 'けいけん', answer: '経験' } ] },
  { kanji: '潔', grade: 5, words: [ { reading: 'いさぎよい', answer: '潔い' }, { reading: 'せいけつ', answer: '清潔' } ] },
  { kanji: '現', grade: 5, words: [ { reading: 'あらわれる', answer: '現れる' }, { reading: 'げんざい', answer: '現在' } ] },
  { kanji: '故', grade: 5, words: [ { reading: 'こしょう', answer: '故障' }, { reading: 'じこ', answer: '事故' } ] },
  { kanji: '効', grade: 5, words: [ { reading: 'きく', answer: '効く' }, { reading: 'こうか', answer: '効果' } ] },
  { kanji: '構', grade: 5, words: [ { reading: 'かまえる', answer: '構える' }, { reading: 'こうぞう', answer: '構造' } ] },
  { kanji: '査', grade: 5, words: [ { reading: 'けんさ', answer: '検査' }, { reading: 'ちょうさ', answer: '調査' } ] },
  { kanji: '災', grade: 5, words: [ { reading: 'わざわい', answer: '災い' }, { reading: 'さいがい', answer: '災害' } ] },
  { kanji: '採', grade: 5, words: [ { reading: 'とる', answer: '採る' }, { reading: 'さいよう', answer: '採用' } ] },
  { kanji: '財', grade: 5, words: [ { reading: 'さいふ', answer: '財布' }, { reading: 'ざいさん', answer: '財産' } ] },
  { kanji: '酸', grade: 5, words: [ { reading: 'すっぱい', answer: '酸っぱい' }, { reading: 'さんそ', answer: '酸素' } ] },
  { kanji: '賛', grade: 5, words: [ { reading: 'さんせい', answer: '賛成' }, { reading: 'さんぴ', answer: '賛否' } ] },
  { kanji: '志', grade: 5, words: [ { reading: 'こころざす', answer: '志す' }, { reading: 'いし', answer: '意志' } ] },
  { kanji: '資', grade: 5, words: [ { reading: 'しげん', answer: '資源' }, { reading: 'しかく', answer: '資格' } ] },

  // ===== 6年生 =====
  { kanji: '異', grade: 6, words: [ { reading: 'ことなる', answer: '異なる' }, { reading: 'いこく', answer: '異国' } ] },
  { kanji: '映', grade: 6, words: [ { reading: 'うつる', answer: '映る' }, { reading: 'えいが', answer: '映画' } ] },
  { kanji: '沿', grade: 6, words: [ { reading: 'そう', answer: '沿う' }, { reading: 'えんがん', answer: '沿岸' } ] },
  { kanji: '拡', grade: 6, words: [ { reading: 'かくだい', answer: '拡大' }, { reading: 'かくちょう', answer: '拡張' } ] },
  { kanji: '革', grade: 6, words: [ { reading: 'かわ', answer: '革' }, { reading: 'かいかく', answer: '改革' } ] },
  { kanji: '閣', grade: 6, words: [ { reading: 'ないかく', answer: '内閣' }, { reading: 'かくぎ', answer: '閣議' } ] },
  { kanji: '簡', grade: 6, words: [ { reading: 'かんたん', answer: '簡単' }, { reading: 'かんい', answer: '簡易' } ] },
  { kanji: '危', grade: 6, words: [ { reading: 'あぶない', answer: '危ない' }, { reading: 'きけん', answer: '危険' } ] },
  { kanji: '机', grade: 6, words: [ { reading: 'つくえ', answer: '机' }, { reading: 'がくしゅうづくえ', answer: '学習机' } ] },
  { kanji: '疑', grade: 6, words: [ { reading: 'うたがう', answer: '疑う' }, { reading: 'ぎもん', answer: '疑問' } ] },
  { kanji: '吸', grade: 6, words: [ { reading: 'すう', answer: '吸う' }, { reading: 'こきゅう', answer: '呼吸' } ] },
  { kanji: '郷', grade: 6, words: [ { reading: 'きょうど', answer: '郷土' }, { reading: 'こきょう', answer: '故郷' } ] },
  { kanji: '勤', grade: 6, words: [ { reading: 'つとめる', answer: '勤める' }, { reading: 'きんむ', answer: '勤務' } ] },
  { kanji: '系', grade: 6, words: [ { reading: 'けいとう', answer: '系統' }, { reading: 'たいようけい', answer: '太陽系' } ] },
  { kanji: '敬', grade: 6, words: [ { reading: 'うやまう', answer: '敬う' }, { reading: 'けいご', answer: '敬語' } ] },
  { kanji: '警', grade: 6, words: [ { reading: 'けいさつ', answer: '警察' }, { reading: 'けいかい', answer: '警戒' } ] },
  { kanji: '劇', grade: 6, words: [ { reading: 'げき', answer: '劇' }, { reading: 'えんげき', answer: '演劇' } ] },
  { kanji: '穴', grade: 6, words: [ { reading: 'あな', answer: '穴' }, { reading: 'おとしあな', answer: '落とし穴' } ] },
  { kanji: '権', grade: 6, words: [ { reading: 'けんり', answer: '権利' }, { reading: 'じんけん', answer: '人権' } ] },
  { kanji: '憲', grade: 6, words: [ { reading: 'けんぽう', answer: '憲法' }, { reading: 'けんしょう', answer: '憲章' } ] },
];
